# Generated by Django 4.1.3 on 2022-12-07 18:36

from django.db import migrations, models
import django.db.models.deletion
import tinymce.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Size',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('size_name', models.CharField(max_length=255)),
                ('monster_size', models.CharField(max_length=50, verbose_name='monster_size')),
            ],
            options={
                'verbose_name_plural': 'Sizes',
                'ordering': ('size_name',),
            },
        ),
        migrations.CreateModel(
            name='Type',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('monster_type', models.CharField(help_text='Enter the type of the beast/monster', max_length=200, verbose_name='monster type')),
            ],
            options={
                'verbose_name': 'type',
                'verbose_name_plural': 'types',
            },
        ),
        migrations.CreateModel(
            name='Monster',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='name')),
                ('about', tinymce.models.HTMLField(verbose_name='summary')),
                ('image', models.ImageField(blank=True, null=True, upload_to='images', verbose_name='image')),
                ('size', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='monsters', to='dnd_monsters.size')),
            ],
        ),
    ]
