# Generated by Django 4.1.3 on 2022-12-08 11:00

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('dnd_monsters', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='monster',
            options={'ordering': ('-created_at',)},
        ),
        migrations.AlterModelOptions(
            name='type',
            options={},
        ),
        migrations.RemoveField(
            model_name='monster',
            name='size',
        ),
        migrations.RemoveField(
            model_name='size',
            name='monster_size',
        ),
        migrations.AddField(
            model_name='monster',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='monster',
            name='sizes',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='monsters', to='dnd_monsters.size'),
        ),
        migrations.AddField(
            model_name='monster',
            name='types',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='monsters', to='dnd_monsters.type'),
        ),
        migrations.AddField(
            model_name='size',
            name='short_description',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
    ]
