# Generated by Django 4.1.3 on 2022-12-09 07:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dnd_monsters', '0002_alter_monster_options_alter_type_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='monster',
            name='slug',
            field=models.SlugField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='size',
            name='slug',
            field=models.SlugField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='type',
            name='slug',
            field=models.SlugField(default=1),
            preserve_default=False,
        ),
    ]
