# Generated by Django 4.1.3 on 2022-12-07 19:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dnd_monsters', '0002_remove_size_monster_size_size_short_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='monster',
            name='size',
        ),
        migrations.AddField(
            model_name='size',
            name='monster_size',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='sizes', to='dnd_monsters.monster'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='type',
            name='monsters',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='types', to='dnd_monsters.monster'),
            preserve_default=False,
        ),
    ]
