# Generated by Django 4.1.3 on 2022-12-07 19:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dnd_monsters', '0003_remove_monster_size_size_monster_size_type_monsters'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='size',
            name='monster_size',
        ),
        migrations.RemoveField(
            model_name='type',
            name='monsters',
        ),
        migrations.AddField(
            model_name='monster',
            name='sizes',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='monsters', to='dnd_monsters.size'),
        ),
        migrations.AddField(
            model_name='monster',
            name='types',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='monsters', to='dnd_monsters.type'),
        ),
        migrations.AddField(
            model_name='type',
            name='monster_sizes',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='sizes', to='dnd_monsters.size'),
            preserve_default=False,
        ),
    ]
