# Generated by Django 4.1.3 on 2022-12-08 07:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dnd_monsters', '0004_remove_size_monster_size_remove_type_monsters_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='type',
            name='monster_sizes',
        ),
    ]
